In [1]:
import numpy as np


In [2]:
a = 5
b = a
b += 1
a

5

In [15]:
X = np.array([[1,-2,3],
              [-1, 2, 0.1]
              ])
x_mask = X.copy()
x_mask

array([[ 1. , -2. ,  3. ],
       [-1. ,  2. ,  0.1]])

In [16]:
x_mask[x_mask<0] = 0  
x_mask

array([[1. , 0. , 3. ],
       [0. , 2. , 0.1]])

In [28]:
from layers import ReLULayer


In [34]:
%reload_ext autoreload
%autoreload 2

X = np.array([[1,-2,3],
              [-1, 2, 0.1]
              ])
layer = ReLULayer()
output = layer.forward(X)
output_weight = np.random.randn(*output.shape)

def helper_func(x):
    output = layer.forward(x)
    loss = np.sum(output * output_weight)
    d_out = np.ones_like(output) * output_weight
    print ("d_out \n", d_out)
    grad = layer.backward(d_out)
    return grad

print("Answer = ", helper_func(X))

print('Output\n',output)
#print('output_weight\n', output_weight)
#X

d_out 
 [[-1.41668121  1.24549017  0.13181886]
 [-0.79617645  0.23784428  1.07801604]]
dX= [[1. 0. 1.]
 [0. 1. 1.]]
Answer =  [[-1.41668121 -0.79617645 -2.21285765]
 [ 1.24549017  0.23784428  1.48333445]
 [ 0.13181886  1.07801604  1.20983489]]
Output
 [[1.  0.  3. ]
 [0.  2.  0.1]]


In [0]:
print('Output\n',output)
print('output_weight\n', output_weight)