In [1]:
import numpy as np
from gradient_check import check_gradient
import linear_classifer as lc

In [15]:
i = np.arange(2,10,3)
i

array([2, 5, 8])

In [2]:
batch_size = 2
num_classes = 2
num_features = 3
#np.random.seed(42)
W = np.random.randint(-1, 3, size=(num_features, num_classes)).astype(np.float)

In [12]:
W = np.random.randint(-1, 3, size=(num_features, num_classes)).astype(np.float)
print (W, "\n\n", np.square(W), '\n\n', np.sum(np.square(W)))

[[-1. -1.]
 [ 2.  0.]
 [ 0. -1.]] 

 [[1. 1.]
 [4. 0.]
 [0. 1.]] 

 7.0


In [9]:
-1 * -1

1

In [7]:
size_t = (3,4)
predictions = np.random.randint(-5,5, size=size_t).astype(np.float)

size_t = (5)
predictions_sing = np.random.randint(-5,5, size=size_t).astype(np.float)

probs = lc.softmax(predictions)

ti =-1
l = len(probs.shape)
if (l == 1):
    ti = 2
else:
    ti = np.array([1,0,0])

print(l, ti, probs)

lc.cross_entropy_loss(probs, ti)


2 [1 0 0] [[8.78619199e-01 1.18908178e-01 2.17787925e-03 2.94743905e-04]
 [4.57640278e-01 2.27845678e-02 6.19348766e-02 4.57640278e-01]
 [6.62272414e-01 4.46235642e-03 2.43636405e-01 8.96288247e-02]]
2


3.3231538262148224

In [32]:
#soft_max[np.arange(len(predictions)), target_index] -= 1
probs = lc.softmax(predictions)
ti = np.random.randint(0, 4, size=(3, 1)).astype(np.int)
print (ti,"\n", probs,'\n')
probs[np.arange(len(probs)), ti[:,0]] -= 10
print(probs)

[[0]
 [3]
 [3]] 
 [[8.78619199e-01 1.18908178e-01 2.17787925e-03 2.94743905e-04]
 [4.57640278e-01 2.27845678e-02 6.19348766e-02 4.57640278e-01]
 [6.62272414e-01 4.46235642e-03 2.43636405e-01 8.96288247e-02]] 

[[-9.12138080e+00  1.18908178e-01  2.17787925e-03  2.94743905e-04]
 [ 4.57640278e-01  2.27845678e-02  6.19348766e-02 -9.54235972e+00]
 [ 6.62272414e-01  4.46235642e-03  2.43636405e-01 -9.91037118e+00]]


In [19]:
l = np.array([5,5,5,5,5,5])
l / 5

array([1., 1., 1., 1., 1., 1.])

In [34]:
size_t = (3,8)

probs = np.random.randint(1,5, size=size_t).astype(np.float)
gt_bool = np.zeros(size_t, np.float64)
ti = np.array([0,1,5])

print (gt_bool, len(gt_bool))
print (ti)

#for i in range(0, len(gt_bool)):
#    gt_bool[i][ti[i]] = 1

gt_bool[np.arange(len(gt_bool)), ti] = 1

print (gt_bool, len(gt_bool))

print(probs)
m = np.mean(probs, axis=1).mean()
m1 = probs.mean()
print(m,m1)

probs_log = np.log(probs)
loss = -1 * np.sum(gt_bool * probs_log)
print(loss)
#2.5416666666666665 2.5416666666666665
#-0.6931471805599453

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]] 3
[0 1 5]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]] 3
[[4. 4. 2. 1. 4. 4. 2. 3.]
 [1. 4. 2. 2. 2. 2. 4. 4.]
 [2. 3. 3. 4. 3. 4. 1. 3.]]
2.8333333333333335 2.8333333333333335
-4.1588830833596715


In [36]:
np.len(2)

AttributeError: module 'numpy' has no attribute 'len'

In [7]:
p = np.random.randint(-5,5, size=(2,2)).astype(np.float)


print (len(p.shape))
m = np.max(p, axis=1)
m = m[:,None]
print (m , m.shape)
p -= m
print (p)
e = np.exp(p)
print (e)
znam = np.sum(e, axis=1)
print(znam)
znam = znam[:,None]
probs = e / znam

np.sum(probs, axis=1)





2
[[3.]
 [1.]] (2, 1)
[[-2.  0.]
 [ 0. -1.]]
[[0.13533528 1.        ]
 [1.         0.36787944]]
[1.13533528 1.36787944]


array([1., 1.])

In [67]:
def array_2d_sum(x):
    assert x.shape == (2,2)
    return np.sum(x), np.ones_like(x)



l1 , l2 = array_2d_sum(np.array([[3.0, 2.0], [1.0, 0.0]]))
l1

6.0

In [59]:
arr = np.arange(12)
it = np.nditer(arr, flags=['multi_index'],op_flags=['readwrite'])
while not it.finished:
    ix = it.multi_index
    print(it[0], ix,arr[ix])
    it.iternext()

0 (0,) 0
1 (1,) 1
2 (2,) 2
3 (3,) 3
4 (4,) 4
5 (5,) 5
6 (6,) 6
7 (7,) 7
8 (8,) 8
9 (9,) 9
10 (10,) 10
11 (11,) 11


In [2]:
num_test = 6
num_train = 10
dists = np.zeros((num_test, num_train), np.float32)

In [29]:
train_x = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
                    [10,10,10,10,10,10,10,10,10,10,10],
                    [20,20,20,20,20,20,20,20,20,20,20],
                    [30,30,30,30,30,30,30,30,30,30,30],
                    [40,40,40,40,40,40,40,40,40,40,40],
                    [50,50,50,50,50,50,50,50,50,50,50],
                    [60,60,60,60,60,60,60,60,60,60,60],
                    [70,70,70,70,70,70,70,70,70,70,70],
                    [80,80,80,80,80,80,80,80,80,80,80],
                    [90,90,90,90,90,90,90,90,90,90,90]])
c = train_x.copy()
c[0,0] = 15
train_x

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [3]:
test_x = np.array( [[0,1,2,3,4,5,6,7,8,9,10],
                    [1,1,2,3,4,5,6,7,8,9,10],
                    [2,1,2,3,4,5,6,7,8,9,10],
                    [3,1,2,3,4,5,6,7,8,9,10],
                    [4,1,2,3,4,5,6,7,8,9,10],
                    [5,1,2,3,4,5,6,7,8,9,10]])
test_x.shape

(6, 11)

In [141]:
f = np.arange(0,10)
ev = np.array_split(f,5)
train_x[ev[1]]
np.delete(train_x,ev[1],axis=0)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40],
       [50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50],
       [60, 60, 60, 60, 60, 60, 60, 60, 60, 60, 60],
       [70, 70, 70, 70, 70, 70, 70, 70, 70, 70, 70],
       [80, 80, 80, 80, 80, 80, 80, 80, 80, 80, 80],
       [90, 90, 90, 90, 90, 90, 90, 90, 90, 90, 90]])

In [53]:
#v = np.abs(test_x[0] - train_x)
d = np.linalg.norm(test_x[0] - train_x[0],ord=1)
d

55.0

In [54]:
dists[0] = d
dists

array([[55., 55., 55., 55., 55., 55., 55., 55., 55., 55.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]], dtype=float32)

In [55]:
vect = np.array([
    [0,1,2,6],
    [3,4,5,7],
])

vect1 = np.array([
    [10,20,30,40],
    [40,50,60,70],
    [70,80,90,0]
])

In [56]:
vect3 = vect[:,np.newaxis,:]

In [57]:
A = np.sum(np.abs(vect3 - vect1),axis=2)


In [58]:
A

array([[ 91, 211, 243],
       [ 81, 201, 235]])

In [59]:
A.shape

(2, 3)

In [60]:
for i in range (1,2):
    print(1)

1


In [74]:
score = np.zeros((2,2),np.float64)
for i in range (0,1):
    score.fill(0)
    score[1][1] += 59
    print(i)
score

1


array([[ 0.,  0.],
       [ 0., 59.]])

In [73]:
score

array([[ 0.,  0.],
       [ 0., 59.]])

In [77]:
s = np.arange(121)
s.shape

(121,)

In [83]:
for i in range(0,5):
    

array([array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24]),
       array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48]),
       array([49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72]),
       array([73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96]),
       array([ 97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
       110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120])],
      dtype=object)